### ISSUE TITLE
Consider adding Dart to the transpilation target languages, enabling discussions

### ISSUE THREAD

**Issue by JordyScript** [adsharma/py2many#1]
I'm not sure if you are aware of the (abandoned) [Medusa project](https://github.com/lispyclouds/medusa). It is a Python to Dart transpiler. I bring this to your attention for two reasons: 

1. To consider adding Dart as a transpilation target language, possibly making use of parts of the code, or
2. To take inspiration from their general approach and see if any of the ideas explored have merit, regardless of adding Dart as a target.

Personally, I'm very interested in source to source translation, as it would unlock so much potential value for all languages if we were no longer bound by the traditional boundaries of each language. Perhaps you could consider enabling the discussions page for this project, so that people could freely discuss ideas that are not yet at the stage of implementation (issues, pull requests, code), or do you have some other means to facilitate this type of communication among collaborators.

**Comment by adsharma** [comment]
Thank you for your interest in the project. Discussions enabled.

Dart is a possibility. But I didn't see a whole bunch of reusable code in the Medusa repo.

**Comment by adsharma** [comment]
https://github.com/adsharma/py2many/commit/b2f079b0d282ec097f71590e5f50e58ab9beb936 added dart support.
Please send pull requests or open new issues for things that are not working.
