### ISSUE TITLE
jlfmt

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#14]
Where is the jlfmt which is used for Julia files?

It seems to be https://github.com/domluna/JuliaFormatter.jl , however that has a bin called `format.jl`, not `jlfmt`.

**Comment by adsharma** [comment]
This is the script I'm using:

```
#!/usr/bin/env ijulia

using JuliaFormatter

function main(args)
    for file in args
        format_file(file)
    end
end
main(ARGS)
```

Had to do some tweaking since Julia has an unusually high startup time.

**Comment by jayvdb** [comment]
perhaps you could propose/add directory mode to https://github.com/domluna/JuliaFormatter.jl

**Comment by adsharma** [comment]
ijulia is this script:

julia -O0 --compile=min --startup=no $*

**Comment by domluna** [comment]
@adsharma you can do `format("directiory")` and it'll do what you mean referring to as _directory mode_

**Comment by adsharma** [comment]
```
#!/usr/bin/env ijulia

using JuliaFormatter

function main(args)
    for arg in args
        format(arg)
    end
end
main(ARGS)
```

works as suggested. Thanks!
