### ISSUE TITLE
v0.2.0 release

### ISSUE THREAD

**Issue by adsharma** [adsharma/py2many#149]
Most other languages are passing tests now:

SKIPPED [1] tests/test_cli.py:64: infer_ops.kt doesnt compile
SKIPPED [1] tests/test_cli.py:64: infer_ops.nim doesnt compile
SKIPPED [1] tests/test_cli.py:64: expected/str_enum.cpp not found
SKIPPED [1] tests/test_cli.py:64: expected/str_enum.go not found
============ 189 passed, 4 skipped, 5 warnings in 388.63s (0:06:28) ============

79% code coverage

C++/go need string enum support (type inference is done)
Kotlin/Nim needs some type casts (copy-pasta from rust should fix).

**Comment by adsharma** [comment]
@jayvdb first test run with no skips and no failures since you set up CI

https://github.com/adsharma/py2many/pull/156/checks?check_run_id=2494093580

================= 193 passed, 5 warnings in 309.69s (0:05:09) ==================

**Comment by jayvdb** [comment]
Well, that is easy to fix - I have lots of test cases that were not passing for various languages.

And incorporate grumpy test suite https://github.com/adsharma/py2many/issues/116 ;-)

**Comment by adsharma** [comment]
I'm thinking of tagging the tree with 0.2 and uploading a new version to pypi

**Comment by jayvdb** [comment]
Up to you whether you want to merge https://github.com/adsharma/py2many/pull/214 into v0.2.0 .  It fixed the code to work with g++, which seems worth including.

I'd appreciate it if you could also pull in https://github.com/john-michaelburke/py2many/commit/8b7574ad46579405ebed8af386028518d9a692db before cutting the release.  Then my internal project using py2many can use the released version.

**Comment by adsharma** [comment]
https://pypi.org/project/py2many/0.2.1/
