### ISSUE TITLE
Generated rust lambda is invalid

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#15]
test case `lambda.py` is currently `lambda x, y: x + y`.  This is actually rather useless in Python, as the created lambda is thrown away.  Still the result in Rust wont compile.
```rust
error: expected item, found `|`
 --> src/lambda.rs:1:1
  |
1 | |x, y| (x + y);
  | ^ expected item
```

Maybe it should become a comment in Rust (and any other sane language)

A more sensible test case would be

```py
def get_func():
    return lambda x, y: x + y
```

And for that, the generated rust code also doesnt compile atm

```rust
error[E0308]: mismatched types
 --> src/lambda.rs:2:12
  |
1 | fn get_func<RT>() -> RT {
  |             --       -- expected `RT` because of return type
  |             |
  |             this type parameter
2 |     return |x, y| (x + y);
  |            ^^^^^^^^^^^^^^ expected type parameter `RT`, found closure
  |
  = note: expected type parameter `RT`
                    found closure `[closure@src/lambda.rs:2:12: 2:26]`
  = help: every closure has a distinct type and so could not always match the caller-chosen type of parameter `RT`
```

**Comment by adsharma** [comment]
```
myfunc: Callable[[int, int], int] = lambda x, y: x + y
```

This line causes the code generator in multiple languages break. Needs fixup and then the generated code has a better chance of compiling.

The commit above at least makes rustfmt happier.

**Comment by jayvdb** [comment]
2c0c1b9 didnt really make it better.
We now have https://github.com/adsharma/py2many/issues/15 and https://github.com/adsharma/py2many/issues/27 and https://github.com/adsharma/py2many/issues/34

Please lets get the CI in operation so that proposed fixes can be checked more thoroughly.
