### ISSUE TITLE
Unnecessary import in int_enum.rs

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#18]
```rust
warning: unused import: `flagset::FlagSet`
 --> src/int_enum.rs:2:5
  |
2 | use flagset::FlagSet;
  |     ^^^^^^^^^^^^^^^^
```

Which also means that the flagset part of the transpiler isnt being tested.

**Comment by adsharma** [comment]
Creating a Cargo.toml with:

```
flagset = "0.4.0"
```

resolves some of the issues. Whether `use flagset::FlagSet;` is needed or not depends on whether the python code is doing set operations with flags. Yes, the transpiler could be smarter and add this to usings only as necessary.

**Comment by jayvdb** [comment]
I already have a Cargo.toml with that in it, hence only the warning.

I am hoping that when https://github.com/stevedonovan/runner/issues/8 and https://github.com/stevedonovan/runner/issues/7 are fixed we can use it to compile the generated code.
