### ISSUE TITLE
Document supported subset

### ISSUE THREAD

**Issue by adsharma** [adsharma/py2many#205]
Something similar to:

https://mys-lang.org/language-reference.html

**Comment by adsharma** [comment]
### Disallowed features

* Metaclasses
* eval
* dunder magic
* anything that calls into the python runtime (like querying the type of an object at runtime)
* is operator (https://news.ycombinator.com/item?id=27139307)


### Allowed features:

* Everything in coverage.py
* What else do we want to call out?

**Comment by jayvdb** [comment]
I would like to see that we are at least intending to be a superset of https://github.com/pseudo-lang/pseudo/blob/master/docs/ast.md , as that project has stalled and py2many could be a drop-in replacement.

**Comment by jayvdb** [comment]
I think we're still quite a distance from closing this issue.  Or we need more issues to better describe the current features, status and limitations.

**Comment by jayvdb** [comment]
Some big ticket un-currently-supported constructs that are worth mentioning:
- comments https://github.com/adsharma/py2many/issues/354
- f-strings https://github.com/adsharma/py2many/issues/74
- str.format https://github.com/adsharma/py2many/issues/73
- printf style strings
- `__dunder_methods__`, esp `__str__` and `__repr__` https://github.com/adsharma/py2many/issues/177

**Comment by adsharma** [comment]
Came across starlark-go specification. This is a subset of python that's used for configuration files. Java and Go implementations exist. Although this spec is for dynamically typed python, we could probably learn from it or leverage it in other ways:

https://github.com/google/starlark-go/blob/master/doc/spec.md

**Comment by jayvdb** [comment]
A comparison of language features supported by various similar tools would be helpful to determine what people typically want to be supported.
https://github.com/lcompilers/lpython is coming along very quickly.
