### ISSUE TITLE
binit.go doesnt compile

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#23]
```go
cases/infer.go
cases/infer.go:5:6: b declared but not used
```

```go
cases/binit.go:9:4: high declared but not used
cases/binit.go:11:4: low declared but not used
cases/binit.go:19:6: x declared but not used
```

**Comment by adsharma** [comment]
declared but used is mostly fixed in
https://github.com/adsharma/py2many/pull/58

The one instance not fixed is `_x`. In python, this is generally sufficient to silence the linter. But not golang.

```
	for x, _ := range limits {
		bins = append(bins, 0)
		_ = x
	}
```

seems to work.

The other fix that's needed is `reflect.DeepEqual` for comparing slices.

**Comment by jayvdb** [comment]
maybe https://github.com/mbenkmann/goformat or similar could be used instead of gofmt ?

c.f. https://github.com/adsharma/py2many/issues/21

**Comment by adsharma** [comment]
Changes needed to binit.rs to make it pass:

https://paste.ubuntu.com/p/r26NzcFxQm/

**Comment by adsharma** [comment]
> maybe https://github.com/mbenkmann/goformat or similar could be used instead of gofmt ?

Sure - doesn't hurt to have more. If extra formatters cause CI pipeline to slow down, we could turn them off by default and use it sparingly to check generated code.
