### ISSUE TITLE
Python test cases should be runnable scripts

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#25]
In addition to being compile-able, the generated files should also be runnable and their output should be the same as the Python script.  That adds an extra layer of validation.

**Comment by jayvdb** [comment]
https://github.com/adsharma/py2many/pull/35 is needed to get print working on each target, so we can compare them to the python baseline.

**Comment by jayvdb** [comment]
There are still quite considerable differences in how the print function transpiles. Might be better getting `assert` working - should be easier to make it consistent when the assertion is true.

**Comment by jayvdb** [comment]
`assert` isnt supported by many of the target languages.

So it seems the quickest path to getting invocation happening is to inject "empty" `main()` , and maybe fix the bugs related to `pass` so that can be used to make the `main()` truly empty in a consistent way.

**Comment by jayvdb** [comment]
When the current set of PRs are merged, all tests are runnable & comparable and are run in CI on at least one platform.

The `is_script` part of the test rig is then redundant, and installing rust-script is no longer necessary.

The test rig can then be rewritten to make that mandatory for all new test cases, making `INVOKER` the "primary" focus of the test logic (and `COMPILER` an optional step), and maybe even enhanced to require that each test case at least passes for at least one language.

**Comment by jayvdb** [comment]
@adsharma , please review https://github.com/adsharma/py2many/pull/60 and https://github.com/adsharma/py2many/pull/85 (and would you mind restarting that job; the failure looks very unrelated to the changes in the PR.)

**Comment by jayvdb** [comment]
I guess one merge per day is all I am allowed :P

**Comment by adsharma** [comment]
They're all runnable scripts now.
