### ISSUE TITLE
"a" in "ba" fails except Dart and Kotlin

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#257]
`"a" in "ba"` fails for all targets except Dart and Kotlin.

I am guessing that str.split, str.partition, slices, etc also fail, so there is no way to do substring comparison in our tests at present - maybe iterating over the target string may work, but comprehensions dont work so a long for `for` loop would be needed.

**Comment by adsharma** [comment]
https://github.com/adsharma/py2many/pull/263 is a step towards a potential solution
