### ISSUE TITLE
Invalid test case with_open

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#279]
```py
Traceback (most recent call last):
  File "tests/cases/with_open.py", line 7, in <module>
    with NamedTemporaryFile(mode="+") as temp_file:
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/tempfile.py", line 543, in NamedTemporaryFile
    file = _io.open(fd, mode, buffering=buffering,
ValueError: Must have exactly one of create/read/write/append mode and at most one plus
```

Also occurs on Python 3.9

**Comment by adsharma** [comment]
Fix coming. 

https://github.com/adsharma/py2many/issues/283 is for generator support in rust. We can add back the generator test once that is ready. For now I'm deleting it.

with_open code for rust is blocked on having access to the dependent rust library. The generated code passed when I manually tested it.
