### ISSUE TITLE
Nim code should probably use 2 spaces instead of 4.

### ISSUE THREAD

**Issue by treeform** [adsharma/py2many#3]
Great project! This is really neat.

Nim and python use similar indentation style, yet its more idiomatic to use 2 space indent in Nim. 

Very odd, but its true!

**Comment by adsharma** [comment]
The setting is in pynim/transpiler.py. Look for self.indent

Happy to accept a pull req to make it a cmdline param

**Comment by adsharma** [comment]
Fixed by https://github.com/adsharma/py2many/commit/b197ba6e140642a30b75bfc06da25f6a6d51a831
