### ISSUE TITLE
Duplicate main

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#30]
The follow results in two `main()` functions
```py

def main():
	...


if __name__ == "__main__":
	main()
```

Generated rust:
```rust

fn main() {
    ...
}

fn main() {
    main();
}
```

**Comment by adsharma** [comment]
I think the fix for this is to rename all other instances of "main" in the module namespace.
One way to implement this is to write a new transformer which checks for the presence of:

```
if __name__ == "__main__":
```

and if present, do a renaming pass over the entire AST.
