### ISSUE TITLE
Transpiled small python program to rust fails to rustc

### ISSUE THREAD

**Issue by dstromberg** [adsharma/py2many#303]
When I try to transpile this little Python program to Rust:
#!/usr/local/cpython-3.9/bin/python3

import math
import time
import random

def main():
    a = []

    random.seed(time.time())
    t1 = time.time()

    for i in range(0, 5000000):
        b = random.random()
        if b > 0.5:
            c = math.pow(b, 1.546)
        else:
            c = math.pow(b, 0.434232)
        d = math.cos(c + i)
        a.append(math.atan(d))

    t2 = time.time()
    print(t2 - t1)

main()

...I get:
cd p2m && py2many --rust=1 p2m.py
Writing to: .
p2m.py...p2m.rs
error: expected one of `!` or `::`, found `(`
  --> /home/dstromberg/src/home-svn/why-is-python-slow/trunk/p2m/p2m.rs:39:5
   |
39 | main();
   |     ^ expected one of `!` or `::`

Error: ['rustfmt', '--edition=2018', 'p2m.rs'] (code: 1):
NoneNone
cd p2m && rustc p2m.rs
error: expected one of `!` or `::`, found `(`
  --> p2m.rs:39:5
   |
39 | main();
   |     ^ expected one of `!` or `::`

error: aborting due to previous error

make: *** [Makefile:17: p2m-rust-t] Error 1

Am I using a mistmatched version of py2many and rust?

I'm using the git py2many as of 2021-05-28, and rust:
rustc 1.52.1 (9bc8c42bb 2021-05-09)

Thanks!

**Comment by jayvdb** [comment]
The first part of your Python which isnt supported is `main()` at the end.

If you use `if __name__ == "__main__": main()` instead, this will get the script transpilation much further.   We might be able to get this bug fixed easily as a special case, but the Rust transpilation generally has problems with globally scoped parts of a Python script. 

Then we run into other problems, such as
- `random.seed`, `random.random` and `time.time` are not converted into Rust syntax.
- `math.pow`, `math.cos` and `math.atan` are not implemented.

Those can usually be fixed fairly easily by adding entries in https://github.com/adsharma/py2many/blob/19e850e/pyrs/plugins.py#L134

**Comment by adsharma** [comment]
Works after slight modifications. Test case and output:

https://paste.ubuntu.com/p/QpXN4cWB2C/
