### ISSUE TITLE
Empty function fails to compile in nim

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#42]
```py
def main():
	pass
```
becomes
```nim

proc main() =
  /*pass*/
```
---
```py
def main():
	"""Foo"""
```

becomes

```nim
proc main() =
  "Foo"
```

**Comment by adsharma** [comment]
It seems to be called `discard` in nim:

https://stackoverflow.com/questions/48282284/is-there-are-something-like-pythons-pass-statement-in-nim

**Comment by adsharma** [comment]
Let's track the second part of it via:https://github.com/adsharma/py2many/issues/7
