### ISSUE TITLE
Four failures in the main branch

### ISSUE THREAD

**Issue by adsharma** [adsharma/py2many#44]
self = <test_cli.CodeGeneratorTests testMethod=test_cli__<'fib', 'kotlin'>>, case = 'fib', lang = 'kotlin'
self = <test_cli.CodeGeneratorTests testMethod=test_cli__<'rect', 'kotlin'>>, case = 'rect', lang = 'kotlin'
self = <test_cli.CodeGeneratorTests testMethod=test_cli__<'print', 'kotlin'>>, case = 'print', lang = 'kotlin'
self = <test_cli.CodeGeneratorTests testMethod=test_cli__<'print', 'dart'>>, case = 'print', lang = 'dart'

The last one is caused by not being able to find the package `sprintf`. I'm not super familiar with how to install packages with dart.

**Comment by jayvdb** [comment]
I've created a task for dart.

The kotlin failures are in re-formatting, and are generally just https://github.com/adsharma/py2many/issues/28, aka many many other bugs in the Kotlin transpiler.

**Comment by jayvdb** [comment]
See https://github.com/jayvdb/py2many/pull/3 for next batch of CI which will resolve some of this.

But I dont have much interest in fixing the large number of Kotlin generation invalid syntax.

**Comment by adsharma** [comment]
Thanks for figuring out how to handle dart + sprintf for CI
It's harder to make it work for normal development flow (using tox or pytest to run the tests).

In the long term, I'm hoping that we can find a maintainer for each supported language.
I hope to spend an hour or so later today fixing some kotlin bugs.

**Comment by adsharma** [comment]
main is healthy as of acd94ef
