### ISSUE TITLE
PyPI name

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#5]
After getting the package ready for release, please upload to PyPI to reserve the name and so it can be easily re-used via a permanent name.

https://github.com/adsharma/py2many/pull/4 does a lot of the prep needed.  README likely needs a few minor adjustments also.

**Comment by adsharma** [comment]
Thanks for taking an active interest in the project. I'm thinking we should prioritize uploading something to pypi, even if all the known issues are not fixed yet.

I would like to merge 

https://github.com/adsharma/py2many/pull/12

and add some badges about tests passing etc to improve confidence.

Let me know if there are other items you would like to prioritize before we make a 0.1.0 release.

**Comment by jayvdb** [comment]
I would like all of my PRs merged, and would appreciate if they were not edited in the process.

**Comment by adsharma** [comment]
Sounds good. I see there are two non draft PRs that are open. If you could rebase them against main, I'll take another look.
Noted about your preference to not edit PRs.

Also, my default workflow is to "squash and merge" and not create merge commits. It works better if there is one commit per pull request.

**Comment by jayvdb** [comment]
I would appreciate it if you used fast forward merges instead of letting GitHub butcher my commits.
If you wont do that, I will split up my PRs into one atomic change per PR, but you can expect hundreds of PRs instead of a few if we go down that path.

**Comment by jayvdb** [comment]
Please re-open https://github.com/adsharma/py2many/issues/7 per comment there.

**Comment by adsharma** [comment]
Still learning the github commit options

"Rebase and merge" is the behavior I want.

https://docs.github.com/en/github/administering-a-repository/about-merge-methods-on-github

Let me know if you want me to force push something equivalent so your
commits are preserved.

**Comment by jayvdb** [comment]
It is not possible to preserve my commits using GitHub fancy green buttons, unless you use proper branch merging.  All options butcher the commits, adding you as the committer to a different set of commits which may or may not be similar to mine and nobody else can see whether they are what I submitted or you significantly edited them.  You need to use cli git and use fast-forward if you want to preserve other peoples commits and not have a merge commit.

**Comment by jayvdb** [comment]
Other than my PRs, I would like to prioritise https://github.com/adsharma/py2many/issues/37 and https://github.com/adsharma/py2many/issues/39 , as they are `pyflakes` errors, and we should get `pyflakes` into the CI.  That sets a baseline quality, on which to improve.

Also important, is getting `codecov.io` activated on this repo, ensuring that code coverage doesnt decrease.

**Comment by jayvdb** [comment]
I think the most important stuff is in.  IMO, :shipit: 0.1 ;-)

codecov.io tracking of coverage is IMO not worth doing atm, as the coverage stats are very misleading because there is lots of coverage for language-specific transpilation code which is in fact emitting junk code that doesnt compile - that is sort of coverage, at least verifying there are no exceptions, but it isnt coverage showing that the code has the correct logic, which is what the coverage stats suggest.  One way to fix this would be to remove the `tests/cases/foo.lang` files which do not yet compile, as the test harness wont then run the transpilation for that language, removing coverage of the code that sample would have produced.  That might be appropriate if there are only a few testcase-lang combinations not compiling, but it doesnt feel like it is useful atm.

https://github.com/adsharma/py2many/pull/87 isnt worth waiting for IMO.

**Comment by adsharma** [comment]
Sorry I missed your comment. 

Given that C++, Rust and Julia are at 100% pass rate, I think we should ship 0.1 as well.

C++ is an asterisk, since it doesn't support string enums natively.

https://github.com/adsharma/py2many/issues/30 is a good one to fix. I'll put something together today or tomorrow. 
pypi requires having a collaborator. Would you be ok if I add you as one?

**Comment by jayvdb** [comment]
> Would you be ok if I add you as one?

Sure.

**Comment by adsharma** [comment]
https://pypi.org/project/py2many/

**Comment by adsharma** [comment]
Thank you for your contributions @jayvdb. Because of your efforts, this release was of significantly improved quality.
