### ISSUE TITLE
Go int enum values are not accessible

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#75]
An enum is converted to
```go
type Colors int

const (
	RED   Colors = iota
	GREEN        = iota
	BLUE         = iota
)
```

That is a reasonable approach, but needs more plumbing to make it workable.

Any other Python code referring to `RED` needs to use `Colors.RED`, and the go transpiler doesnt covert those `Colors.RED` to be just `RED`.  As a result of `Colors.RED` being copied as-is to the go code, go error is:

> Colors.RED undefined (type Colors has no method RED)

**Comment by adsharma** [comment]
We now have a is_enum(). In visit_Attr, we can check if it's enum and remove "Colors."
