### ISSUE TITLE
"a" in ["a"] broken

### ISSUE THREAD

**Issue by jayvdb** [adsharma/py2many#93]
`"a" in ["a"]` in the ast is an `ast.Compare` and an `ast.In`.

This works for lists and sets when transpiling to Rust, however it does not work for dicts in Rust, and it fails for all container types in the other target languages.

Also for target cpp, it causes an exception:
```py
py2many/py2many/cli.py:185: in main
    _process_once(settings, source, outdir)
py2many/py2many/cli.py:133: in _process_once
    f.write(transpile(source_data, settings.transpiler))
py2many/py2many/cli.py:45: in transpile
    code = transpiler.visit(tree) + "\n"
py2many/py2many/clike.py:80: in visit
    return super().visit(node)
/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py:407: in visit
    return visitor(node)
py2many/py14/transpiler.py:285: in visit_Module
    buf = [self.visit(b) for b in node.body]
py2many/py14/transpiler.py:285: in <listcomp>
    buf = [self.visit(b) for b in node.body]
py2many/py2many/clike.py:80: in visit
    return super().visit(node)
/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py:407: in visit
    return visitor(node)
py2many/py14/transpiler.py:97: in visit_FunctionDef
    body = "\n".join([self.visit(n) for n in node.body])
py2many/py14/transpiler.py:97: in <listcomp>
    body = "\n".join([self.visit(n) for n in node.body])
py2many/py2many/clike.py:80: in visit
    return super().visit(node)
/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py:407: in visit
    return visitor(node)
py2many/py14/transpiler.py:353: in visit_Assert
    return "assert({0});".format(self.visit(node.test))
py2many/py2many/clike.py:80: in visit
    return super().visit(node)
/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py:407: in visit
    return visitor(node)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <py14.transpiler.CppTranspiler object at 0x10c2b3640>, node = <ast.Compare object at 0x10c2b3ac0>

    def visit_Compare(self, node):
        if isinstance(node.ops[0], ast.In):
>           return self.visit_Any(node)
E           AttributeError: 'CppTranspiler' object has no attribute 'visit_Any'
```

**Comment by jayvdb** [comment]
basic dict functionality (`a = {0: 1}; print(a)`) works currently in Dart and Kotlin, and the same functionality with sets works for Dart only.

The printing of sets and dicts doesnt work because of missing `Display` trait on HashSet/HashMap, which is because the print logic is using `{}` instead of `{:?}`, which is a separate minefield wrt compatibility with Python.

**Comment by adsharma** [comment]
That looks like a bug I introduced sometime back. Probably mistaken global replace.

-            return self.visit_Any(node)
+            return self.visit_In(node)

**Comment by adsharma** [comment]
This should be fixed by https://github.com/adsharma/py2many/pull/98

**Comment by jayvdb** [comment]
> This should be fixed by #98

Add use of this syntax to `coverage.py` test case ?

**Comment by adsharma** [comment]
https://github.com/adsharma/py2many/tree/coverage_container_in

cpp and go fail. Everything else passes after this commit

**Comment by jayvdb** [comment]
If you dont want to get cpp and go working (yet), you could use this syntax in the `global.py` test case, which already fails on go and c++ for other reasons.  Having this syntax will be very helpful in creating other container based tests cases, and those usually fail on cpp & go anyway.

**Comment by adsharma** [comment]
global* pass now for cpp/go
